"""Source-grounded reference material; historical display claims are not current recommendations."""
QUESTION_GROUPS = [
 ('The profession','The AI-Enabled Lawyer, p. 17',[
 'What work deserves a law license?',
 'Which legal tasks exist because information used to be scarce?',
 'What should remain human?',
 'What should become a product or process?',
 'How does advocacy change when AI reads first?',
 'What should clients pay for?',
 'How will novices become experts?',
 'Who bears the error?',
 'Who receives the gain?',
 'Can technology close the justice gap without scaling bad advice?',
 'How should lawyers lead mixed teams?',
 'What previously uneconomic solution can now exist?']),
 ('AI and legal work','AI for Law Students, pp. 13–14',[
 'Which parts of legal work are valuable because they produce an answer—and which are valuable because they force the lawyer to think?',
 'What happens when powerful, accurate legal analysis becomes abundant?',
 'Which tasks can be delegated to AI, and which decisions must remain attributable to a person? Where should we all agree that humans do the work?',
 'Will we change how we write, as humans, so that the AI tools reading our work handle it better?',
 'Will we change how we write to avoid “sounding like an AI”? Will we start writing more like AI because we read so much of it now?',
 'How much can a lawyer rely on an AI system without understanding how it reached its answer, particularly when tools do not show the steps?',
 'What does meaningful supervision look like when an agent performs hundreds of actions in minutes?',
 'When does using AI become part of competent representation so that not using it is an ethical violation?',
 'How should firms preserve institutional knowledge when much of the work occurs inside private AI conversations?',
 'Will AI reduce drudgery or merely increase expected output? Will it increase the data and paper we need to deal with?',
 'How do we preserve dissent when AI presents one polished recommendation as the natural answer? What happens if judges, lawyers, and clients use the same flawed tools?',
 'Will lawyers investigate less because AI can construct a plausible story from incomplete facts?',
 'What new kinds of legal work will AI create?']),
 ('AI and clients','AI for Law Students, pp. 14–15',[
 'Should clients decide whether AI is used in their matters?',
 'What must lawyers disclose about that use?',
 'Should clients receive the savings created by AI?',
 'Can clients understand enough about AI to consent meaningfully?',
 'Does a client have a right to speak with a human lawyer?',
 'Can a lawyer delegate emotionally or morally significant conversations to AI?',
 'What happens when an AI system knows more about the client than the lawyer does?',
 'Should AI infer goals the client has not expressed?',
 'Whose interests does the system serve when the client, lawyer, firm, insurer, and vendor want different things?',
 'Can an AI-generated recommendation subtly steer a client toward the outcome preferred by the lawyer or institution?',
 'How should lawyers protect clients whose vulnerabilities make them unusually susceptible to machine persuasion?',
 'What happens when a client relies on an AI summary instead of the lawyer’s actual advice?',
 'Who owns the client’s prompts, facts, strategy, and resulting work product?',
 'Can information shared with an AI remain confidential, privileged, and genuinely erasable?',
 'Should clients be able to inspect how AI influenced important advice or decisions?']),
 ('AI and the public’s experience of law','AI for Law Students, pp. 15–16',[
 'Does the public have a right to know when AI has shaped a government decision?',
 'Does a person have a right to a human hearing?',
 'How can someone challenge a decision when no person can explain how it was reached?',
 'Who helps people determine whether AI-generated legal advice is accurate?',
 'Should public-facing legal AI be regulated as information, software, or professional service?',
 'What remedies should exist when free or inexpensive legal AI causes harm?',
 'Can legal information be personalized without quietly becoming legal advice?',
 'Will AI make law understandable—or give people false confidence that they understand it?',
 'Can access to a chatbot substitute for access to representation?',
 'What happens when people can generate claims but cannot investigate, litigate, or enforce them?',
 'Will courts become less accessible if they assume everyone has AI assistance?',
 'Should public institutions provide an official legal AI rather than leaving access to private vendors?',
 'Must government systems support different languages, disabilities, literacy levels, and cultural contexts?',
 'Can AI help people comply with law before disputes arise?',
 'Could AI make rights practically usable rather than merely available on paper?',
 'How do we prevent landlords, employers, creditors, insurers, and governments from using AI to scale pressure faster than individuals can scale resistance?']),
 ('AI and legal institutions','AI for Law Students, pp. 16–17',[
 'Which exercises of state or government power may never be automated?',
 'Can the government rely on a proprietary system that the public cannot inspect?',
 'What process is due when an AI system affects liberty, benefits, employment, immigration status, or family integrity?',
 'Should judges disclose when AI helped analyze a case or draft an opinion?',
 'May judges use AI trained on material the parties never had an opportunity to address?',
 'What happens when different judges use different models to interpret the same law?',
 'Can AI-generated judicial reasoning create legitimate precedent?',
 'Will AI encourage courts to produce more decisions but devote less thought to each one?',
 'How should courts handle an explosion of inexpensive filings, discovery, and appeals?',
 'Can public defenders compete if prosecutors possess better models, data, and infrastructure?',
 'Should litigants have access to the tools used to investigate, score, prosecute, sentence, or supervise them?',
 'Can a government satisfy its duty to give reasons by offering an AI-generated explanation after the decision?',
 'Should legislatures use AI to model how proposed laws will affect different communities?',
 'Who is accountable when lawmakers adopt machine-generated language they do not fully understand?',
 'Can regulation remain democratic when technical complexity gives vendors more influence? How should lawyers consider vendors’ influence on the legal system?']),
 ('Law’s role in an AI society','AI for Law Students, pp. 17–19',[
 'Do people need a right to know when they are interacting with AI?',
 'Do people need a right to human review?',
 'Should people be able to refuse consequential AI decisions?',
 'Who owns a person’s voice, likeness, style, behavior, and inferred identity?',
 'Can privacy law protect people when AI can infer sensitive facts that were never collected?',
 'Should individuals be able to see, correct, or delete the profiles AI systems construct about them?',
 'May institutions treat people differently based on conduct an AI predicts but that has never occurred?',
 'How should discrimination law address harms produced by correlations rather than explicit classifications?',
 'When must a person be judged as an individual rather than as a member of a predicted group?',
 'Who owns the knowledge created from society’s collective writing, art, behavior, and experience?',
 'Should private companies control the infrastructure through which people learn, communicate, work, and obtain legal help?',
 'How much concentration of AI power is compatible with democracy?',
 'Should advanced AI be treated as a public utility, licensed profession, regulated product, or something new?',
 'Who may deploy systems capable of surveillance, persuasion, impersonation, or autonomous action?',
 'What duties should developers owe people who never agreed to use their systems?',
 'Should AI companies bear responsibility for foreseeable downstream uses of their products?',
 'How should liability work when harm emerges from interactions among developers, deployers, users, data, and autonomous agents?',
 'What evidence should a company need before releasing a system into high-stakes settings?',
 'How should law protect children growing up with AI tutors, companions, evaluators, and persuaders?',
 'What happens to freedom of thought when systems can predict which argument will influence each person?',
 'How should law respond when AI blurs the lines around what is verifiable evidence?',
 'Who should receive the wealth produced when AI draws upon generations of publicly created knowledge?',
 'What obligations do governments or others owe people and communities displaced by AI?',
 'Should efficiency gains produce shorter working lives, greater public wealth, or larger private returns?',
 'How do we preserve room for unusual, minority, and genuinely new ideas when AI favors statistically likely answers?',
 'What human capacities should society deliberately preserve even if machines can outperform us?',
 'How much environmental cost should society accept for AI systems?',
 'Can national law govern systems that operate globally?',
 'What happens when countries adopt radically different rules about autonomy, privacy, speech, and surveillance?',
 'Should future generations have representation in decisions about transformative AI?',
 'What rights might people need that existing constitutions never contemplated in an age of AI?',
 'Are we using AI to improve the legal and social order we want, or allowing available technology to choose that order for us?'])
]

GLOSSARY_ADDITIONS=[
 ['AGI / artificial general intelligence','The source glossary uses AGI for a hypothetical system matching or exceeding human capability across essentially all cognitive tasks. Definitions and claims about its achievement are contested; this entry is a definition, not a current capability assessment.','basics'],
 ['Alignment','Alignment concerns whether a system pursues intended goals and behaves in the desired way. For the work discussed here, examine the actual objective, permissions, and behavior rather than assuming the system shares the client’s interests.','agents'],
 ['Chain of thought','This term describes intermediate reasoning generated by a model before its answer. A displayed explanation or summary is not independent evidence that a conclusion is correct. Use sources and observable checks to evaluate the work.','basics'],
 ['Chatbot','A chatbot is a conversational interface. It may be connected to retrieval, documents, or agent functions; the interface alone does not tell you what the surrounding system can do.','basics'],
 ['Deep learning','Deep learning uses many-layered neural networks to learn patterns from data. The introductory guide includes it as background for understanding how language models are developed.','basics'],
 ['GPT','GPT stands for generative pre-trained transformer and also appears in OpenAI model names. It is not a generic name for every AI system.','basics'],
 ['Jailbreak','A jailbreak is an attempt to make a model bypass its behavioral restrictions through an input. The source distinguishes this from instructions hidden in retrieved material, commonly called prompt injection.','agents'],
 ['Neural network','A neural network is a mathematical structure with connected layers whose numerical settings are adjusted during learning. It is background vocabulary, not a description of how a particular legal answer was verified.','basics'],
 ['RLHF','Reinforcement learning from human feedback uses human judgments as part of shaping a model’s behavior after initial training. It does not establish that every subsequent output is accurate.','basics'],
 ['TAR / technology-assisted review','TAR uses predictive techniques in document review, including learning from reviewers’ decisions to rank likely responsiveness. The source distinguishes it from generating new summaries or prose.','basics'],
 ['Temperature','Temperature is a generation setting associated with variation in output. Its availability and effect depend on the product. Changing it does not establish the accuracy of a legal response.','basics'],
 ['Training data','Training data is the material used to develop a model’s learned patterns. It is different from the source packet supplied for a particular assignment.','basics'],
 ['Transformer','A transformer is a model architecture associated with modern language systems. The introductory glossary includes it to explain the T in GPT; you do not need to implement one to direct legal work.','basics'],
 ['Turing test','The source glossary describes Alan Turing’s proposal for considering whether a machine’s conversation can be distinguished from a person’s. Appearing human is different from meeting the standard for a legal assignment.','basics']
]

# Each row identifies source-derived teaching and where a reader can find it without completing an activity.
COVERAGE=[
 ('The AI-Enabled Lawyer','1–3','Professional identity; frame, judge, design, counsel, challenge, own; expanded roles; systems fluency','lawyer','0–4','Expanded reading'),
 ('The AI-Enabled Lawyer','4','Human-first frame; AI-assisted expansion; lawyer-grade audit; human revision and judgment; document and improve','method','4','Full five-stage explanation'),
 ('The AI-Enabled Lawyer','5','Five questions before prompting; green/yellow/red levels of control','permission','0–1','All questions and categories in the reading'),
 ('The AI-Enabled Lawyer','6','External and internal risk; four combinations and matching controls','permission','2','All four situations explained'),
 ('The AI-Enabled Lawyer','7','Six forms of purposeful friction, including divergence, adversarial prompting, reviewed sources, distance, and annotated reliance','think','1–4','Expanded reading'),
 ('The AI-Enabled Lawyer','8','Seven professional duties and subordinate-lawyer responsibility','ethics','0–4','Reading plus linked primary authority'),
 ('The AI-Enabled Lawyer','9','Learning through human-first work and questions before replacement prose','think','0–4','Reading and visible tutor example'),
 ('The AI-Enabled Lawyer','10','Eight management functions and six management failures','agents','0–4','Full reading; failures named and explained'),
 ('The AI-Enabled Lawyer','11','The twelve-part agent work order','agents','1','Complete readable reference and worked assignment'),
 ('The AI-Enabled Lawyer','12–13','Nine process stages; user, outcome, sequence, judgment, control, learning; NIST perspective','process','0–4','Full reading'),
 ('The AI-Enabled Lawyer','14','Ten harness elements; staged sequence; limits of cross-model critique','harness','0–4','Full reading'),
 ('The AI-Enabled Lawyer','15','Six lawyer contributions to building and six prototype-to-pilot standards','building','0–4','Full reading, no checklist required'),
 ('The AI-Enabled Lawyer','16','Six parts of a lawyering playbook','playbook','0–4','Full reading and prepared entry'),
 ('The AI-Enabled Lawyer','17','Twelve open professional questions','leadership','0–2','Reading and complete question reference'),
 ('The AI-Enabled Lawyer','18','Eight closing capabilities and the profession’s wider imagination and reach','leadership','3–4','Full reading'),
 ('Using AI This Semester','1','Twelve before/during/after practices','permission; method; ethics; think','multiple','Distributed across relevant chapters; source checklist retained'),
 ('Using AI This Semester','2','Five self-assessment questions; accept/modify/reject; limits of research claim','think','1','All questions and method visible'),
 ('Using AI This Semester','2','Seven stopping circumstances','permission','3','All circumstances visible'),
 ('Using AI This Semester','2','Use note and limits of disclosure as a substitute for review','ethics','3–4','Visible example'),
 ('AI for Law Students','1–2','Language and lawyer value; opportunity beyond efficiency; independence; shaping norms','lawyer; leadership','multiple','Expanded reading, mixed-audience framing'),
 ('AI for Law Students','2–4','Training, tokens, parameters, post-training, tools, generation, variation, uneven capability','basics','0–4','Full conceptual explanation'),
 ('AI for Law Students','4–6','Models versus applications; context, saved references, prompting as assignment; memory','basics; harness; prompting','multiple','Full reading, product limits distinguished'),
 ('AI for Law Students','6–8','Hallucination, source verification, retrieval, reasoning models, agents, harnesses','basics; agents; harness','multiple','Full concepts; historical case counts not recast as current data'),
 ('AI for Law Students','9–10','Practice uses and product categories','basics; writing','multiple','Categories and uses explained; historical vendors not a buying guide'),
 ('AI for Law Students','10–11','Professional duties, court requirements, confidential information','ethics; permission','multiple','Reading and linked primary references'),
 ('AI for Law Students','11–12','Learning rather than outsourcing; tutoring, role-play, challenge, feedback','think; method','multiple','Reading; optional activities remain supplementary'),
 ('AI for Law Students','12–13','Exploration suggestions and further-reading resources','sources; think; method','multiple','Concepts in reading; bibliographic leads retained in source notes'),
 ('AI for Law Students','13–19','All five groups of open questions','questions','all','Complete readable collection with minor copyediting'),
 ('AI for Law Students','19–22','Glossary','glossary','all','Missing vocabulary restored; current-status claims not repeated as current fact'),
 ('Leveling Up Your AI Prompting','2–3','Iterative engagement; process; when, how, and improvement over time','method; playbook','multiple','Full reading'),
 ('Leveling Up Your AI Prompting','4–7','Three opportunities; first work; limits on uses you cannot judge; guidance','lawyer; permission; prompting','multiple','All opportunities and decision limits explained'),
 ('Leveling Up Your AI Prompting','8–10','Six collaboration practices; variable amount of human-first work','method; think','multiple','All six practices in plain reading'),
 ('Leveling Up Your AI Prompting','11–13','Employee-departure facts and AI prioritization comparison','think','2','Complete fact passage and visible comparison; no exercise required'),
 ('Leveling Up Your AI Prompting','14–19','Direct/context/show; expand/pressure-test/identify; options and follow-up','method; prompting','multiple','Full reading'),
 ('Leveling Up Your AI Prompting','20–24','Fee-table original and different prompt results','writing','1','Original and all three principal comparisons visible'),
 ('Leveling Up Your AI Prompting','25–31','Scale for model and reviewer; isolate headings or subject line','method','3','Reading and concrete examples'),
 ('Leveling Up Your AI Prompting','32–39','Ten principles; variables; priority; quoted material; self-checking; reuse; style specification','prompting; aiisms','multiple','Full reading with qualifications recorded'),
 ('Leveling Up Your AI Prompting','40–53','Dog-toy introduction, concrete narration, annotated exemplars, diagnosis/candidates/evaluation/explanation/choice','writing','2','Visible before/opinion excerpt and process explanation'),
 ('Leveling Up Your AI Prompting','54','AI assistance at multiple points inside research and analysis','method','1–2','Reading'),
 ('Leveling Up Your AI Prompting','55–57','Stonebridge and Falcon material facts and conditions','writing','3–4','Complete originals and clearly identified prepared revisions'),
 ('Leveling Up Your AI Prompting','58–65','Two ways to address AI-isms; words, sentences, formatting, substance','aiisms','0–4','Full reading'),
 ('Leveling Up Your AI Prompting','66','Data-retention before/after illustration','aiisms; sources','3','Unsupported legal ceiling and enforcement details not adopted; limitation explicit'),
 ('Leveling Up Your AI Prompting','67–72','Weak employment paragraph and authorship-contrast exercises','aiisms','2','Weak paragraph and diagnosis visible; no authorship detector implied'),
 ('Leveling Up Your AI Prompting','73–77','Own style, house style, challenge the description, save style block','aiisms','4','Full reading'),
 ('Leveling Up Your AI Prompting','78–87','Rewriting, editing, drafting, summarizing, organizing, analysis, learning, playbooks, checklists','writing; method; playbook','multiple','Uses integrated in reading; heading-only example slides do not supply missing examples'),
 ('Original graphing discussion','whole guide','Dependencies, parallel work, source-linked handoffs, stop/return paths, human decisions, manual operation, tests, automation','graphing','0–8','Complete worked sequence available without running the simulation')
]
EDITORIAL_NOTES=[
 'The four subject areas and each numbered framework retain separate functions. A workflow map, a knowledge graph, the five-stage responsible-use process, six collaboration practices, ten prompting principles, and twelve-part work order are not merged.',
 'Chapter and section addresses, activity IDs, the local-storage key, and the backup identifier are preserved. Optional companion forms retain existing saved field keys.',
 'Prepared advice revisions and added workflow examples are identified as guide additions. Original Stonebridge, Falcon, fee-table, employee-departure, and deliberately weak AI-isms passages retain their supplied meaning and qualifications.',
 'The original slide on a supposed three-year GDPR ceiling and a specific enforcement penalty supplies no supporting authority. Those legal assertions are not adopted as law. The guide explicitly explains that limitation rather than replacing them with invented support.',
 'The employment “What we found” slide refers to a Vance passage and a word count that do not match the immediately preceding Ms. Chen paragraph. Its diagnosis is not presented as a verbatim answer key to that paragraph; the guide identifies its own explanation as prepared commentary.',
 'Some slides supply only an “Example” heading. The guide does not pretend that those slides contain a worked example. The developed examples in the reading are identified by source or as guide additions.',
 'The introductory PDF’s historical model names, adoption figures, sanctions totals, product guarantees, and legal-tool benchmark rates have not been freshly verified. They are not presented as current statistics or product recommendations. Core distinctions and the category map remain in the reading.',
 'The source’s strong prohibitions on unreviewable work and its red/yellow/green framing remain substantive guidance. A color or completed form is not treated as permission, and jurisdiction-specific professional duties require the actual authority.',
 'The source’s short-term-memory and system-prompt explanations describe different products at a high level. The guide distinguishes a saved reference arrangement from software-enforced controls and does not promise that a folder enforces permissions.',
 'The fixed rhythm and numerical voice-vector examples are identified as illustrative variables, not mandatory style rules. The user’s express request for full sentences and natural, non-formulaic prose governs this edition.',
 'The four-minute pause remains a suggested teaching practice. The source itself limits the inference from research with science students; the guide retains that qualification.',
 'The source’s questions are open inquiries, not established legal conclusions or a grading rubric. The full readable reference restores questions previously available only as selected reflection prompts. Minor punctuation and obvious typographical errors are edited without supplying answers.',
 'The source glossary is expanded for readable use. Historical claims about what has or has not been achieved are not converted into current assertions. The technical vocabulary is explanatory, not an endorsement of any product.',
 'The legal note about the full text of Model Rule 5.2 is a separately sourced clarification, not language attributed to the teaching slides. Primary references remain distinguishable from the author’s teaching material.'
]
