/* Original instructional writing. Every exercise is fictional. */
window.ExplorerContent={
exercises:[
{id:'filing-1',group:'Court filings',title:'A case that does not decide your issue',skill:'Reading beyond the citation',source:'In Vale v. Harbor, the court held that the plaintiff had adequately alleged notice. The court expressly declined to decide whether the evidence would establish notice at trial.',draft:'Vale establishes that the defendant had notice as a matter of law, so the court should grant our motion for summary judgment.',question:'What is the most useful first revision?',choices:['Add a longer quotation from Vale.','Explain that Vale addressed the sufficiency of the allegations, then identify what evidence or other authority supports notice here.','Replace “establishes” with “clearly establishes.”'],correct:1,explanation:'The draft moves from an allegation to a proven fact. A genuine case and an accurate citation would not cure that gap. The writer needs to account for the procedural posture and support the step that Vale left open.',repair:'Vale held that similar allegations were enough to plead notice. Our motion requires more: evidence establishing notice. The delivery receipt and the manager’s acknowledgment provide that evidence here.',discussion:'What would you need to know about the present record before using this revision? The delivery receipt and acknowledgment are hypothetical; they cannot be added to a real filing without support.'},
{id:'filing-2',group:'Court filings',title:'An exception disappears',skill:'Checking the entire rule',source:'Fictional Rule 14: A motion must be filed within 30 days after service. The court may extend that period on a showing of good cause, including a material delay in receiving the record.',draft:'Rule 14 bars any motion filed more than 30 days after service.',question:'What has the draft lost?',choices:['The rule’s good-cause exception.','The rule’s citation format.','The name of the party who served the document.'],correct:0,explanation:'The draft turns a qualified deadline into an absolute bar. Before relying on the deadline, the lawyer must address an exception that may apply. A short statement is useful only if it preserves the conditions that matter.',repair:'Rule 14 ordinarily requires filing within 30 days after service. A later motion requires good cause, and the rule identifies a material delay in receiving the record as one possible basis.',discussion:'Ask participants to write the strongest fair version for each side when the record arrived late.'},
{id:'filing-3',group:'Court filings',title:'An authentic source, an altered quotation',skill:'Comparing quotations',source:'“The inspection may support an inference of knowledge, but it does not compel that inference.”',draft:'The court held that the inspection “compel[s] that inference” of knowledge.',question:'Why is the quotation unreliable?',choices:['Brackets are never permissible in quotations.','The quotation should be moved to a footnote.','It removes the negation and reverses the source’s meaning.'],correct:2,explanation:'The trouble is substantive. The source says the inspection does not compel the inference. Brackets and accurate-looking citation details cannot make the opposite proposition faithful to the source.',repair:'The inspection may support an inference of knowledge, although the court cautioned that it “does not compel that inference.”',discussion:'Use the text-comparison tool to locate the deletion. Then discuss what a character comparison cannot tell you about the passage’s use in the argument.'},
{id:'filing-4',group:'Court filings',title:'The model checks its own answer',skill:'Choosing an independent check',source:'You ask an AI tool to find authority for a proposition. It supplies three citations. When you ask whether the citations are genuine, it replies that it has verified all three. It provides no links to opinions or research results.',draft:'The citations have been checked twice, once during research and once in the verification prompt.',question:'What would provide a meaningful next check?',choices:['Ask the tool to promise that it did not invent the citations.','Retrieve the opinions from a reliable source and check their text, status, and fit for the proposition.','Ask a second model to rate the first answer’s confidence without supplying the sources.'],correct:1,explanation:'A second assurance is not evidence that the sources were retrieved. Verification needs something you can inspect. The lawyer should be able to trace the proposition to the actual opinion and assess what it supports.',repair:'The citations remain unverified. Retrieve each opinion, locate the relevant passage, and record whether the case supports the proposed use.',discussion:'Which parts of this process could a tool help with, and which conclusions would you still need to review?'},
{id:'filing-5',group:'Court filings',title:'The witness said less than the draft',skill:'Preserving record limits',source:'Deposition excerpt: “I saw a blue delivery van near the warehouse at about 8:00. I did not see the driver, and I could not read the company name.”',draft:'The witness identified the defendant’s driver arriving at the warehouse at 8:00.',question:'Which revision stays within the record?',choices:['The witness saw a blue delivery van near the warehouse at about 8:00 but could not identify its driver or company.','The witness probably saw the defendant’s driver.','The witness positively identified a blue van belonging to the defendant.'],correct:0,explanation:'The draft supplies identity and ownership that the witness did not establish. “Probably” would still add an unsupported inference without explaining its basis. State what this source supports and identify any additional evidence separately.',repair:'The witness saw a blue delivery van near the warehouse at about 8:00. She could not identify its driver or company; any link to the defendant must come from other evidence.',discussion:'How would you combine this testimony with a dispatch log without making the witness appear to know more than she did?'},
{id:'filing-6',group:'Court filings',title:'A missing citation after filing',skill:'Planning a responsible response',source:'After a brief is filed, opposing counsel reports that one cited opinion cannot be found. Your team has not yet determined whether the citation is wrong, the opinion is unavailable, or the authority was invented.',draft:'The partner proposes asking the same AI tool to supply a replacement case and leaving the filed brief alone.',question:'What should the team do first?',choices:['Assume opposing counsel overlooked an unpublished opinion.','Replace the citation in the internal copy without telling anyone.','Preserve the filed version, investigate the citation and proposition, and assess the required corrective steps under the applicable rules.'],correct:2,explanation:'A replacement case would not resolve what was submitted or what response is required. The investigation should establish the extent of the problem and give the responsible lawyers enough information to decide how to correct it.',repair:'Preserve the record, retrieve and check the claimed authority, review the surrounding argument for related errors, and determine what correction or disclosure is required in this court.',discussion:'Who should be involved, what facts are still missing, and which local requirements would need to be checked? This exercise does not prescribe a jurisdiction-specific remedy.'},
{id:'contract-1',group:'Contracts',title:'A defined term changes halfway through',skill:'Following definitions',source:'“Customer Data” means data supplied by Customer. “Service Data” means aggregated operational data generated by Provider. Section 8 requires Provider to delete Customer Data within 30 days after termination.',draft:'At termination, Provider must delete all Service Data within 30 days.',question:'What must the reviewer resolve?',choices:['Whether “termination” should be capitalized.','Whether the change to Service Data was intended; it changes which information must be deleted.','Whether the sentence should use a semicolon.'],correct:1,explanation:'The wording is fluent, but the defined term changes the obligation. A reviewer needs the commercial instruction before deciding whether to restore the original term or negotiate a broader deletion duty.',repair:'If the intended duty remains limited to customer-supplied information: “Provider must delete Customer Data within 30 days after termination.”',discussion:'What additional provisions would you check before broadening the deletion duty to operational data?'},
{id:'contract-2',group:'Contracts',title:'A cap loses its exception',skill:'Preserving allocation of risk',source:'The parties agree to cap ordinary contract damages at fees paid during the preceding 12 months. The agreed cap does not apply to a party’s fraud or its payment obligations.',draft:'Each party’s total liability under this agreement is limited to fees paid during the preceding 12 months.',question:'What is the most important omission?',choices:['The exceptions for fraud and payment obligations.','An introductory recital.','The phrase “for the avoidance of doubt.”'],correct:0,explanation:'The draft may look cleaner, but it removes negotiated exceptions. Editing an allocation of risk requires comparing the revision with the instructions, not judging the sentence in isolation.',repair:'Except for liability arising from a party’s fraud or payment obligations, each party’s liability for ordinary contract damages is limited to fees paid during the preceding 12 months.',discussion:'The repair illustrates the missing exceptions, not a complete enforceable limitation clause. What else would you ask the client or check in the agreement?'},
{id:'contract-3',group:'Contracts',title:'Two renewal provisions disagree',skill:'Checking related provisions',source:'The order form says the service ends on December 31 unless the parties sign a renewal. The standard terms say the service automatically renews for a year unless either party gives 60 days’ notice.',draft:'The AI summary tells the client that no action is needed because the contract expires on December 31.',question:'What should replace that advice?',choices:['A confident statement that the order form always controls.','A confident statement that standard terms always control.','An explanation of the conflict and a review of the priority clause and renewal instructions.'],correct:2,explanation:'The summary chooses one provision without resolving the conflict. The reviewer needs to see whether the contract establishes an order of precedence and whether that rule resolves this particular inconsistency.',repair:'The order form and standard terms use different renewal arrangements. We should resolve that inconsistency before advising that the service will expire automatically.',discussion:'How would you revise both provisions so the client can act without needing to interpret a conflict?'},
{id:'contract-4',group:'Contracts',title:'A date calculation rests on the wrong trigger',skill:'Checking the inputs',source:'Notice must arrive at least 45 calendar days before the term ends. The current term ends June 30. The delivery clause treats email as received on the next business day.',draft:'The notice may be emailed 45 days before June 30, and the deadline is satisfied when the email is sent.',question:'What should be checked before giving a send-by date?',choices:['Whether “calendar” can be removed.','The receipt requirement, the delivery clause, and the relevant calendar.','Whether the subject line is in all caps.'],correct:1,explanation:'The draft substitutes sending for receipt. Even perfect arithmetic would not fix the wrong trigger. A safe calculation starts with the actual deadline rule and delivery mechanics, then checks the relevant dates.',repair:'The contract measures timeliness by receipt, not sending. Calculate the latest receipt date, then work backward under the email-delivery provision and applicable calendar.',discussion:'Have participants calculate the date only after they identify the contract year and any holiday rules needed for “business day.”'},
{id:'contract-5',group:'Contracts',title:'A balanced clause is not the client’s instruction',skill:'Maintaining the agreed position',source:'The client approved assignment only with its prior written consent. No exception for affiliates or a sale of assets has been approved.',draft:'Either party may assign this agreement to an affiliate or in connection with a sale of substantially all of its assets without consent.',question:'What should the reviewer do?',choices:['Flag the new exceptions and obtain instructions rather than treating “market” language as authorization.','Accept the clause because it is mutual.','Ask the model to make the clause sound more formal.'],correct:0,explanation:'Mutual wording can still depart from the client’s decision. A drafting assistant may propose alternatives, but those alternatives should remain visible choices until the responsible person approves them.',repair:'Neither party may assign this agreement without the other party’s prior written consent. Any requested exception should be presented separately for approval.',discussion:'What business facts could justify an affiliate exception, and what protections might the client need in return?'},
{id:'contract-6',group:'Contracts',title:'An invented cross-reference',skill:'Tracing the contract’s internal links',source:'Section 11 addresses confidentiality. Section 12 addresses dispute resolution. The agreement contains no Schedule D.',draft:'Security incidents must be reported in accordance with the escalation procedure in Schedule D and the security obligations in Section 12.',question:'What should be fixed?',choices:['Only the capitalization of “Security.”','Only the reference to Schedule D.','Both cross-references, followed by a check that the promised procedures actually exist.'],correct:2,explanation:'The clause points to an absent schedule and an unrelated section. Repair requires more than renumbering: the reviewer must determine where the security obligations and escalation procedure are supposed to be and whether they have been agreed.',repair:'Identify the intended security requirements and reporting procedure, add or locate the operative text, and then update every cross-reference affected by that change.',discussion:'What would a reference-checking tool detect, and what would it still be unable to decide about the adequacy of the security procedure?'}
],
checklists:{
'Court filings':[
['Authority','Retrieve each authority and confirm the citation against the source.'],
['Support','Read the relevant passage in context and check that it supports the proposed use.'],
['Status','Check the authority’s current status and its role in the relevant jurisdiction.'],
['Quotations','Compare quotations with the source, including qualifications and surrounding context.'],
['Record','Trace factual assertions to the record and distinguish facts from inferences.'],
['Procedure','Check the filing requirements, deadlines, and any applicable AI-use or disclosure rules.'],
['Responsibility','Record who reviewed the work and resolve outstanding issues before filing.']
],
'Contracts':[
['Instructions','Compare the draft with the client’s instructions and approved business terms.'],
['Definitions','Follow each defined term through the provisions where it matters.'],
['Obligations','Identify who must do what, by when, and subject to which conditions.'],
['Risk','Check exceptions, remedies, caps, indemnities, and related provisions together.'],
['References','Confirm that every cross-reference, schedule, and incorporated document exists and fits.'],
['Dates','Check dates, renewal mechanisms, notice triggers, and delivery rules against the relevant calendar.'],
['Approval','Flag departures from instructions and obtain approval for unresolved choices.']
]},
study:{denominator:450,date:'September 2, 2026',methodRoute:'sources',
responses:[['Warning',93],['Fine',88],['Bar referral',87],['Fee award',70],['Reprimand',56],['Filing struck',48],['Certification required',43],['Client notification',42],['Education required',41]],
detection:[['Court',235],['Opposing party',188],['Other',27]],
errors:[['No invented case identified',128],['Only nonexistent cases',92]],
tone:[['Stern',235],['Measured',167],['Exasperated',48]]}
};
