/* Pure data functions. No services, tracking, or external libraries. */
(function(root){
'use strict';
const STATES={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',DC:'District of Columbia',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming'};
const DEFAULT_MAPPING={title:'Case Name',court:'Court',countries:'State(s)',date:'Date',actors:'Party(ies)',tool:'AI Tool',items:'Hallucination Items',outcome:'Outcome',money:'Monetary Penalty',discipline:'Professional Sanction',alleged:'Alleged',disputed:'Vendor Disputed',disputeNote:'Vendor Disputed Explanation',pointer:'Pointer',source:'Source',details:'Details',field:'Legal Field Primary',field2:'Legal Field Secondary',state:''};
const split=v=>[...new Set(String(v||'').split(/\s*;\s*/).map(s=>s.trim()).filter(Boolean))];
const clean=v=>String(v??'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();
const yes=v=>/^(yes|true|1)$/i.test(String(v).trim());
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeURL(url,base){if(!String(url||'').trim())return '';try{const u=new URL(String(url||''),base||'https://www.damiencharlotin.com/');return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
function amount(raw,sentinel=true){const s=String(raw||'').trim();if(!s)return {value:null,currency:'',status:'missing',raw:s};const m=s.match(/^([\d,]+(?:\.\d+)?)\s*([A-Za-z]{3})?$/);if(!m)return {value:null,currency:'',status:'unparsed',raw:s};const v=Number(m[1].replace(/,/g,'')),currency=(m[2]||'').toUpperCase();if(!Number.isFinite(v))return {value:null,currency,status:'unparsed',raw:s};return {value:sentinel&&v===1?null:v,currency,status:sentinel&&v===1?'unknown':'known',raw:s};}
function inferState(court,countries){if(!countries.includes('USA'))return '';const sorted=Object.entries(STATES).sort((a,b)=>b[1].length-a[1].length);for(const [code,name] of sorted){if(new RegExp('\\b'+name+'\\b','i').test(court))return code;}if(/\bD\.?C\.?\b/i.test(court))return 'DC';return '';}
function validDate(v){const s=String(v||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return '';const d=new Date(s+'T00:00:00Z');return !Number.isNaN(+d)&&d.toISOString().slice(0,10)===s?s:'';}
function normalise(obj,i,mapping=DEFAULT_MAPPING,meta={}){const get=k=>clean(obj[mapping[k]]);const countries=split(get('countries'));const actors=split(get('actors')).map(x=>x==='Governement Lawyer'?'Government Lawyer':x);const items=get('items');const errors=[...new Set(items.split(/\s*\|\|\s*/).map(x=>x.split('|')[0].trim()).filter(Boolean))];const types=[...new Set(errors.map(x=>x.split(':')[0].trim()))];const outcome=get('outcome');const tool=get('tool');const fields=[...new Set([...split(get('field')),...split(get('field2'))])];const r={id:'r'+(i+1),title:get('title')||'Untitled record',court:get('court'),countries,actors,date:validDate(get('date')),dateRaw:get('date'),tool:tool||'Not recorded',types,errors,items,outcome,outcomes:split(outcome),money:amount(get('money'),meta.oneIsUnknown!==false),discipline:yes(get('discipline')),alleged:yes(get('alleged')),disputed:yes(get('disputed')),disputeNote:get('disputeNote'),pointer:get('pointer'),source:get('source')?safeURL(get('source'),meta.sourceBase):'',details:get('details'),fields};r.state=get('state')||inferState(r.court,countries);r.stateInferred=!get('state')&&!!r.state;r.search=[r.title,r.court,countries.join(' '),actors.join(' '),tool,items,outcome,r.details,fields.join(' ')].join(' ').toLowerCase();return r;}
function rowsFrom(dataset){const cols=dataset.columns;return cols?dataset.rows.map(row=>Object.fromEntries(cols.map((c,i)=>[c,row[i]??'']))):dataset.rows;}
function normalizeDataset(dataset,mapping=DEFAULT_MAPPING){const raw=rowsFrom(dataset);if(!Array.isArray(raw)||raw.length>50000)throw Error('Please use a dataset with no more than 50,000 rows.');return raw.map((r,i)=>normalise(r,i,mapping,dataset.meta));}
function has(values,label){return label==='Not recorded'?(!values||values.length===0):values.includes(label);}
function filterRows(rows,f={}){const q=(f.q||'').toLowerCase().trim().split(/\s+/).filter(Boolean);return rows.filter(r=>(!q.length||q.every(t=>r.search.includes(t)))&&(!f.country||has(r.countries,f.country))&&(!f.actor||(f.actor==='@legal'?r.actors.some(a=>['Lawyer','Government Lawyer','Federal Defender','Prosecutor','Paralegal'].includes(a)):has(r.actors,f.actor)))&&(!f.type||has(r.types,f.type))&&(!f.outcome||(f.outcome.toLowerCase()==='not recorded'?!r.outcomes.length:r.outcomes.some(x=>x.toLowerCase()===f.outcome.toLowerCase())))&&(!f.tool||r.tool===f.tool)&&(!f.field||has(r.fields,f.field))&&(!f.state||r.state===f.state)&&(!f.from||r.date&&r.date>=f.from)&&(!f.to||r.date&&r.date<=f.to)&&(!f.money||r.money.status!=='missing')&&(!f.discipline||r.discipline)&&(!f.excludeAlleged||!r.alleged)&&(!f.excludeDisputed||!r.disputed)&&(!f.saved||f.saved.includes(r.id)));}
function count(rows,key){const c={};rows.forEach(r=>{let v=typeof key==='function'?key(r):r[key];if(!Array.isArray(v))v=[v||'Not recorded'];if(!v.length)v=['Not recorded'];[...new Set(v)].forEach(x=>{c[x]=(c[x]||0)+1;});});return Object.entries(c).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));}
function series(rows){const known=rows.filter(r=>r.date);if(!known.length)return [];const counter=Object.fromEntries(count(known,r=>r.date.slice(0,7)));const dates=known.map(r=>r.date).sort();let cur=dates[0].slice(0,7),last=dates.at(-1).slice(0,7),total=0,out=[];while(cur<=last&&out.length<1200){const n=counter[cur]||0;total+=n;out.push({month:cur,count:n,total});const d=new Date(cur+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);cur=d.toISOString().slice(0,7);}return out;}
const median=v=>{const s=v.filter(Number.isFinite).sort((a,b)=>a-b);return s.length?s.length%2?s[(s.length-1)/2]:(s[s.length/2-1]+s[s.length/2])/2:null;};
function parseCSV(text){text=String(text).replace(/^\uFEFF/,'');const out=[];let row=[],val='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quote&&n==='"'){val+='"';i++;}else if(!quote&&val!==''){val+=c;}else quote=!quote;}else if(!quote&&(c===','||c==='\n'||c==='\r')){row.push(val);val='';if(c!==','){if(c==='\r'&&n==='\n')i++;if(row.some(x=>x!==''))out.push(row);row=[];}}else val+=c;}if(quote)throw Error('A quoted CSV field was not closed. Check the file and try again.');if(val||row.length){row.push(val);out.push(row);}if(!out.length)throw Error('This file has no rows.');const headers=out.shift().map(x=>x.trim());if(new Set(headers).size!==headers.length||headers.some(x=>!x))throw Error('Each CSV column needs a unique, nonempty heading.');const bad=out.findIndex(r=>r.length!==headers.length);if(bad!==-1)throw Error('Row '+(bad+2)+' has a different number of fields than the header.');return {columns:headers,rows:out};}
function csvCell(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function toCSV(rows){return '\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n');}
function compareText(a,b,normalize=false){if(a.length>20000||b.length>20000)throw Error('Please compare passages of 20,000 characters or fewer.');const norm=s=>normalize?s.replace(/\s+/g,' ').trim():s;if(norm(a)===norm(b))return {equal:true,parts:[{kind:'same',text:b}]};const aa=norm(a).match(/\s+|[^\s]+/g)||[],bb=norm(b).match(/\s+|[^\s]+/g)||[];if(aa.length*bb.length>2500000)return {equal:false,limited:true,parts:[{kind:'del',text:norm(a)},{kind:'ins',text:norm(b)}]};const dp=Array.from({length:aa.length+1},()=>new Uint16Array(bb.length+1));for(let i=aa.length-1;i>=0;i--)for(let j=bb.length-1;j>=0;j--)dp[i][j]=aa[i]===bb[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);const parts=[];let i=0,j=0;function add(kind,text){if(parts.at(-1)?.kind===kind)parts.at(-1).text+=text;else parts.push({kind,text});}while(i<aa.length||j<bb.length){if(i<aa.length&&j<bb.length&&aa[i]===bb[j]){add('same',aa[i++]);j++;}else if(i<aa.length&&(j===bb.length||dp[i+1][j]>=dp[i][j+1]))add('del',aa[i++]);else add('ins',bb[j++]);}return {equal:false,parts};}
const api={STATES,DEFAULT_MAPPING,split,clean,yes,escape,safeURL,amount,inferState,validDate,normalise,rowsFrom,normalizeDataset,filterRows,count,series,median,parseCSV,toCSV,compareText};if(typeof module!=='undefined')module.exports=api;else root.ExplorerCore=api;
})(typeof window!=='undefined'?window:globalThis);
