/* The main reading page. Study aggregates never inherit case-library filters. */
const FINDING_SECTIONS=[['people','Who appears'],['experience','Experience & practice'],['courts','Courts'],['workflows','How AI was used'],['errors','What went wrong'],['responses','Court responses'],['trends','Changes over time'],['teaching','For your teaching']];
const F=window.ExplorerFindings;
const pct=(value,total)=>total?(value>0&&value/total<0.005?'<1':Math.round(value/total*100))+'%':'—';
function findingJump(id,label){return `<button class="small" data-action="jump-finding" data-target="${id}">${h(label)}</button>`;}
function findingSection(id,title,intro,body,source='study'){
 const sourceLabel=source==='database'?`${n(records.length)} database records · ${date(dataset.meta.snapshot)}`:source==='courts'?'1,378 U.S. records · September 2, 2026':source==='teaching'?'Teaching suggestions':'450-order study · September 2, 2026';
 return `<section id="finding-${id}" class="finding-section" aria-labelledby="finding-title-${id}"><header class="finding-heading"><span class="finding-source ${source==='database'?'database':''}">${h(sourceLabel)}</span><h2 id="finding-title-${id}" tabindex="-1">${title}</h2><p>${intro}</p></header>${body}</section>`;
}
function teachingNote(text){return `<aside class="teaching-note"><strong>For teaching</strong><p>${text}</p></aside>`;}
function figureNote(text){return `<p class="figure-note">${text}</p>`;}
function dataBars(entries,denom=0){return bars(entries,null,entries.length,denom);}
function dataTable(headers,rows,caption=''){
 return `<div class="table-wrap finding-table"><table>${caption?`<caption>${caption}</caption>`:''}<thead><tr>${headers.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>i===0?`<th scope="row">${x}</th>`:`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
function insightCaseButton(label,filters){return `<button class="small" data-action="finding-cases" data-filters="${h(JSON.stringify(filters))}">${h(label)} →</button>`;}
function participantRows(rows){
 const legal=new Set(C.filterRows(rows,{actor:'@legal'}).map(r=>r.id));
 const prose=new Set(rows.filter(r=>r.actors.includes('Pro Se Litigant')).map(r=>r.id));
 return [['Lawyers & legal staff',legal.size],['Self-represented litigants',prose.size],['Judges',rows.filter(r=>r.actors.includes('Judge')).length],['Experts',rows.filter(r=>r.actors.includes('Expert')).length],['Arbitrators',rows.filter(r=>r.actors.includes('Arbitrator')).length],['Participant not recorded',rows.filter(r=>!r.actors.length).length]];
}
function findingsPeople(){
 if(dataset.meta.custom){return findingSection('people','Who and what appears in this dataset?','These charts use the participant and jurisdiction columns mapped when the dataset was imported.',`<div class="grid2 equal">${panel('Participants as supplied','Labels may overlap within one record.',dataBars(C.count(records,'actors'),records.length))}${panel('Jurisdictions as supplied','No categories are inferred from the study dataset.',dataBars(C.count(records,'countries').slice(0,12),records.length))}</div>`,'database');}

 const all=participantRows(records),us=records.filter(r=>r.countries.includes('USA')),american=participantRows(us),legal=C.filterRows(records,{actor:'@legal'});
 const rowCount=records.filter(r=>r.actors.length>1).length;
 const table=all.map(([label,num],i)=>[h(label),`${n(num)} <span class="muted">(${pct(num,records.length)})</span>`,`${n(american[i][1])} <span class="muted">(${pct(american[i][1],us.length)})</span>`]);
 return findingSection('people','Who appears in the decisions?',`Self-represented litigants account for ${pct(all[1][1],records.length)} of the included records, while lawyers and legal staff appear in ${pct(legal.length,records.length)}. Both groups belong in the discussion, but the questions they raise for educators are different.`,
 `<div class="grid2 equal">${panel('Participants, worldwide and in the United States','These are decisions involving each group, not counts of individual people.',dataTable(['Participant',`Worldwide<br><small>n = ${n(records.length)}</small>`,`United States<br><small>n = ${n(us.length)}</small>`],table)+figureNote(`${n(rowCount)} records name more than one participant type, so columns need not add up to 100%. Legal staff includes paralegals; the lawyer group includes prosecutors and public defenders.`)+`<div class="actions">${insightCaseButton('Read lawyer-related decisions',{actor:'@legal'})}${insightCaseButton('Read pro se decisions',{actor:'Pro Se Litigant'})}</div>`)}${panel('Where the records come from','Counts use the jurisdiction labels in the included source.',dataBars(C.count(records,'countries').slice(0,8),records.length)+figureNote('The database is a collection of reported decisions, not a representative sample of legal work. Differences in publication and reporting affect which cases can be found.'))}</div>`+
 teachingNote('A professional-responsibility class can examine the lawyer’s review and supervision duties. An access-to-justice discussion can ask what support a person without counsel would need to check an AI-generated filing.'),'database');
}
function findingsExperience(){
 const exp=F.experience,firm=F.firm_size;
 return findingSection('experience','The lawyers span the career ladder',`Among the ${n(exp.resolved)} lawyers with a verified bar-admission year, the median was ${exp.median} years since admission at the first order in the study. The record includes both new lawyers and lawyers with decades in practice.`,
 `<div class="stats">${stat('Median time since admission','21 years','394 lawyers with an admission year; measured at their first study order.')}${stat('At least 20 years',pct(exp.at_least_20,exp.resolved),`${n(exp.at_least_20)} of 394 lawyers with a resolved admission year.`)}${stat('Fewer than 5 years',pct(exp.under_5,exp.resolved),'21 of 394; this is a share of the study, not an error rate.')}${stat('Solo or firm of 2–10',pct(329,395),'329 of 395 private-practice lawyers assigned one size band.')}</div>`+
 `<div class="grid2 equal">${panel('Years since first verified bar admission','The full distribution among 394 lawyers.',dataBars(exp.dist.map(([label,value])=>[label+' years',value]),394)+figureNote('The middle half falls between 13 and 31 years; the range is 0–56. Admission years could not be resolved for 26 of the 420 identified lawyers. Time since admission is a proxy, not a measure of skill or continuous practice.'))}${panel('Practice size','One firm-size band for 395 private-practice lawyers.',dataBars(firm.bands,395)+figureNote('Another 23 lawyers were in government, legal aid, public defense, in-house, or other nonprivate roles. One person lacked an organization and one changed size bands. The study cannot establish which practice settings carry greater risk.'))}</div>`+
 `<div class="grid2 equal">${panel('Representation in the underlying case','450 orders; this counts orders rather than distinct lawyers.',dataBars(F.caseSide,450)+figureNote('Plaintiff, appellant, and petitioner together account for 326 orders (72%). Those are separate procedural roles, not a single practice specialty.'))}${panel('What the source documents say about pronouns','Anonymous aggregates for the same 420-person roster.',dataBars([['He/him-family wording',269],['She/her-family wording',104],['No acceptable wording found',47]],420)+figureNote('These categories describe wording in court documents and professional sources. They do not establish gender identity or gender-specific risk. The review did not classify people from names or photographs.')+`<div class="finding-aside"><h3>Some lawyers appear more than once.</h3><p>37 of the 420 identified lawyers appear in multiple orders. For 13 of them, that is only because one case produced two orders. Multiple entries should not automatically be described as repeated misconduct.</p></div>`)}</div>`+
 teachingNote('Training should reach experienced practitioners as well as students and junior lawyers. A useful exercise asks participants to demonstrate their checking process, rather than treating years in practice as evidence that the process is reliable.'));
}
function findingsCourts(){
 const levels=[['Federal',934],['State',442],['Tribal',1],['Arbitral forum',1]],tiers=[['Trial courts',955],['Intermediate appellate courts',329],['Bankruptcy courts',33],['Administrative bodies',33],['Courts of last resort',24],['Unclassified',4]];
 const stateRows=Object.entries(F.us_states).sort((a,b)=>b[1].all-a[1].all||a[0].localeCompare(b[0]));
 return findingSection('courts','The record reaches well beyond federal trial courts','The court classifications below come from the study’s September 2 review of 1,378 U.S. records. They preserve its order-checked classifications rather than guessing court levels from abbreviations in the newer database.',
 `<div class="grid2 equal">${panel('Federal and state systems','All 1,378 U.S. records in this study snapshot.',dataBars(levels,1378)+figureNote('The lawyer-related subset contains 360 federal and 186 state records. A larger federal share may reflect the greater availability of searchable federal orders; it does not establish that state practice is safer.'))}${panel('Court level and type','All 1,378 U.S. records in the same snapshot.',dataBars(tiers,1378)+figureNote('New York’s Supreme Court is generally a trial court. The source study checked ambiguous labels against the orders, including appellate and bankruptcy exceptions.'))}</div>`+
 `<div class="grid2 equal">${panel('Courts with the most recorded decisions','The study merged label variants and grouped divisions of the same appellate court.',dataBars(F.us_top_courts)+figureNote('Counts include all participant types. The two Florida federal districts are both shown because they tie at the cutoff.'))}${panel('States with the most recorded decisions','Study snapshot; the counts include state and federal courts assigned to each state.',dataTable(['State','All','Lawyer','Pro se'],stateRows.slice(0,10).map(([key,value])=>[h(C.STATES[key]||key),n(value.all),n(value.lawyer),n(value.prose)]))+`<div class="finding-aside"><h3>Every state and D.C. appears.</h3><p>In this snapshot, Montana, North Dakota, South Dakota, and West Virginia have no lawyer-related decision. That means none was recorded here—not that no error occurred.</p></div>`+figureNote('84 U.S. records have no home state; Puerto Rico, Guam, and the Northern Mariana Islands are reported separately. Participant categories can overlap.')+`<details class="accordion"><summary>All state counts</summary>${dataTable(['State','All','Lawyer','Pro se','Federal','State court'],stateRows.map(([key,value])=>[h(C.STATES[key]||key),n(value.all),n(value.lawyer),n(value.prose),n(value.federal),n(value.state)]))}</details>`)}</div>`+
 teachingNote('Use trial and appellate examples together. Ask students to identify the court, the procedural setting, and the source of its authority before they compare outcomes.'),'courts');
}
function findingsWorkflows(){
 const who=[['Signing lawyer',187],['Client',10],['Law clerk, intern, or student',9],['Paralegal or nonlawyer staff',9],['Associate or junior lawyer',7],['Co-counsel or local counsel',6],['Contract or freelance lawyer',5],['Unknown or denied',217]];
 const use=[['Research to find authority',174],['Drafting portions of a document',121],['Drafting an entire document',62],['Checking the AI’s own work',12],['Editing or formatting citations',8],['Summarizing a record or transcript',6],['Other unspecified use',1],['Use not stated',193]];
 return findingSection('workflows','How did AI enter the work?','Where an order identifies the person who generated the material, it is usually the signing lawyer: 187 of 233 orders, or 80%. The user is unknown or denied in the remaining 217 orders.',
 `<div class="grid2 equal">${panel('Who generated the material','All 450 orders, including those with no identified user.',dataBars(who,450))}${panel('How AI was used','More than one use can be recorded in an order.',dataBars(use,450)+figureNote('Research appears in 174 of the 257 orders that describe a use (68%), or 39% of all 450 orders. Both percentages describe the same count with different denominators.'))}</div>`+
 `<div class="finding-band"><div><span class="finding-big">81%</span><h3>of orders do not name the product</h3><p>364 of 450 orders leave it unnamed. Among the 86 that name one, ChatGPT appears in 35 and legal-research platforms with an AI layer in 23. Only three orders identify a ChatGPT version or tier.</p></div><div><h3>Editing and checking also need review.</h3><p>The study records AI use for editing or citation formatting in 8 orders and for checking its own work in 12. A document can acquire errors after the initial research or drafting is done; a final comparison with the sources still matters.</p><p class="figure-note">The product counts do not measure how often any product is used or how often it fails. These orders cannot rank product reliability.</p></div></div>`+
 teachingNote('Ask learners to map the whole workflow, including research, drafting, editing, and final review. Then have them specify which checks must be repeated after an AI-assisted revision.'));
}
function findingsErrors(){
 const errors=[['Nonexistent case',317],['Real case does not support the proposition',237],['Misquotation of a real case',197],['Case name and reporter citation do not match',103],['Incorrect pinpoint citation',35],['Fabricated or misquoted statute or rule',31],['Other defect',31],['Invented record fact, witness, or exhibit',21],['Overruled or outdated authority',10]];
 const explanations=[['No explanation recorded',179],['Admitted the problem and apologized',138],['Delegated and did not check',67],['Called it a typo or formatting error',50],['Denied using AI',44],['Blamed another person',44],['Checked some citations, but not all',32],['Personal hardship, health, or family',32],['Time pressure or deadline',27],['Blamed software or a technical error',23],['Did not know AI could fabricate',22],['Trusted a legal-specific or paid tool',22],['First time using AI',15],['Workload or understaffing',14],['Thought the tool was a search engine or database',9],['Other explanation',54]];
 return findingSection('errors','Finding the case is only part of the check','In 128 of the 450 orders, the filing was defective even though no invented case was identified. Of those 128 orders, 101 involved a problem with a real case, such as an inaccurate quotation or an unsupported proposition.',
 `<div class="finding-band"><div><span class="finding-big">28%</span><h3>contained defects without an invented case</h3><p>128 of 450 orders. Checking whether the cases exist would not have resolved the errors in these filings.</p></div><div><span class="finding-big">20%</span><h3>involved only nonexistent cases</h3><p>92 of 450 orders. Many other filings combined several kinds of error, so a single successful check should not end the review.</p></div></div>`+
 `<div class="grid2 equal">${panel('What was wrong with the filing','Study coding; a single order can appear in several categories.',dataBars(errors,450))}${panel('Explanations recorded in the orders','These are explanations offered, not necessarily explanations the court accepted.',dataBars(explanations,450)+figureNote('Explanations overlap. The study’s combined “did not know / search engine / first use” group covers 35 distinct orders; adding those three individual categories would overcount.'))}</div>`+
 teachingNote('Give students an authentic case paired with an inaccurate proposition, quotation, or pinpoint. Ask them to retrieve the relevant passage and explain exactly how far the authority supports the draft.'));
}
function findingsResponses(){
 const detection=[['Court identified the problem',235],['Opposing counsel identified it',188],['Self-disclosed',12],['Unknown',11],['Other',3],['Unclear',1]];
 const candor=[['Admitted after the court asked',162],['Denied, then admitted',26],['Denied throughout',17],['Added more defective citations',37],['Admitted immediately or self-disclosed',22],['Admission; timing not stated',1]];
 const sanctions=[['Warning',93],['Monetary payment to the court',88],['Court referral to a bar authority',87],['Fees or costs to the opponent',70],['Public reprimand or admonishment',56],['Filing struck',48],['Certification or disclosure required',43],['Client notification ordered',42],['Legal education ordered',41],['Order published or distributed',28],['Self-report to a bar ordered',13],['Claim, case, or appeal dismissed',13],['Suspension from that court',9],['Disqualification or removal',8],['Client fee refund or forfeiture',7],['Contempt',4],['Pro hac vice admission revoked',4]];
 const aggravating=[['Lack of candor or delayed admission',144],['Burden on the court',144],['Repeat conduct',103],['Errors in the show-cause response',48],['Experience cited as a reason to know better',36],['Prior warnings in the same case',21],['Harm to the client',17]];
 const mitigating=[['Apology or remorse',111],['Training, policy, or other remedial steps',97],['Prompt admission',65],['No bad faith found',45],['Personal circumstances',32],['No prior discipline',30],['Prompt withdrawal of the filing',24]];
 return findingSection('responses','What did courts do, and what did they consider?','The orders describe more than monetary penalties. They include corrections to filings, referrals, education requirements, and consequences for clients. The lawyer’s response after discovery is a separate part of the record.',
 `<div class="grid2 equal">${panel('Who found the problem','All 450 coded orders.',dataBars(detection,450))}${panel('How the lawyer responded','265 orders discuss the response; 185 do not.',dataBars(candor,265)+figureNote('Denial or adding further bad citations appears in 80 of these 265 orders (30%). This describes coded responses; it does not establish the effect of candor on the sanction.'))}</div>`+
 `<div class="grid2 equal">${panel('Court responses recorded in the study','Categories can overlap; counts are out of 450 orders.',dataBars(sanctions,450)+figureNote('Another 26 orders carry an “other” response category. The study codes 124 as having none of the listed sanctions at that stage; this does not establish that no consequences followed. A referral is not a final disciplinary result.'))}${panel('What courts weighed','Factors expressly identified in the coded orders; categories overlap.',`<h3 class="subfigure-title">Aggravating factors</h3>${dataBars(aggravating,450)}<h3 class="subfigure-title spaced">Mitigating factors</h3>${dataBars(mitigating,450)}`)}</div>`+
 `<div class="grid2 equal">${panel('Fines and fee awards are different','Published study amounts separated by the recipient of the payment.',dataTable(['Payment','Known amounts','Median'],F.fine_fee.map(x=>[h(x.label),n(x.n),'$'+n(x.median)]))+figureNote('These are study-classified amounts, not all monetary entries in the public database. The fees-and-costs median is $7,000 across 35 amounts; the payment-to-court median is $1,625 across 86 amounts. Missing amounts are not zero.')+`<p class="finding-paragraph">The study’s largest verified award in one order was <strong>$94,704.38 in fees and costs</strong> in <em>Couvrette v. Wisnovsky</em>. The database’s $110,204 entry combines that later award with an earlier $15,500 penalty; it is not a single fine.</p><p class="figure-note">As of September 2, 2026, the study’s public-source searches had not verified a disbarment. That is a dated search result, not proof that none occurred. Suspension from one court and loss of a law license are different consequences.</p>`)}${panel('The language courts used','Subjective classifications from a single AI-assisted coding pass.',dataBars(T.study.tone,450)+figureNote('235 orders were coded stern, 167 measured, and 48 exasperated. 105 included explicit language about escalating consequences. These categories are descriptive, not an independent measure of judicial attitude.'))}</div>`+
 `<div class="grid2 equal">${panel('Authorities appearing in the orders','Counts record mentions, not a finding that each authority applies in every case.',dataBars(F.authorities.map(x=>[x.label,x.n]),450))}${panel('Earlier decisions the orders cite','243 of the 450 orders cite at least one earlier sanctions decision.',dataBars(F.cited.slice(0,8))+figureNote('A useful starting point for studying how later courts use earlier sanctions cases. Read the cited decision and the later court’s explanation before treating their circumstances as interchangeable.'))}</div>`+
 teachingNote('Extend the exercise beyond spotting the original error. Ask learners to draft the next communication to the court or client, identify what must be corrected, and explain which parts of the record need further checking.'));
}
function findingsTrends(includeStudy){
 const chart=panel('Decisions by month','The full active dataset, without case-library filters.',timeline(records),`<div class="tabs"><button class="small ${!ui.cumulative?'active':''}" data-action="timeline" data-mode="monthly">Monthly</button><button class="small ${ui.cumulative?'active':''}" data-action="timeline" data-mode="total">Cumulative</button></div>`);
 const yearly=C.count(records.filter(r=>r.date),r=>r.date.slice(0,4)).sort((a,b)=>a[0].localeCompare(b[0]));
 const extra=includeStudy?panel('The U.S. lawyer–pro se mix stayed fairly steady','September 2 study snapshot; percentages use all U.S. records in each period.',dataTable(['Period','Lawyer / staff','Pro se','All records'],F.us_half_by_party.filter(x=>x.half>='2025').map(x=>{const legal=(x.Lawyer||0)+(x['Lawyer (mixed)']||0)+(x['Government lawyer']||0)+(x.Paralegal||0),total=Object.entries(x).filter(([k])=>k!=='half').reduce((s,[k,v])=>s+v,0);return [x.half==='2026-H2'?'Jul.–Aug. 2026':x.half.replace('-H1',' · Jan.–Jun.').replace('-H2',' · Jul.–Dec.'),n(legal)+' ('+pct(legal,total)+')',n(x['Pro se']),n(total)];}))+figureNote('The lawyer-related share is about 39–41% in these periods. More recorded decisions do not, by themselves, establish a changing participant mix or a changing error rate.')):panel('Records by year','Partial years are not full-year comparisons.',dataBars(yearly));
 return findingSection('trends','How has the record changed over time?','The chart follows decision dates, not the date each record was discovered or added. Recent months can still be incomplete, and the database does not count all AI-assisted work.',`<div class="grid2 equal">${chart}${extra}</div>`,'database');
}
function teachingCase(query,title,question){
 const candidates=records.filter(r=>r.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.date||'').localeCompare(a.date||'')),r=candidates[0];
 if(!r)return '';
 return `<article class="teaching-case"><span class="finding-source">Case for discussion</span><h3>${h(title)}</h3><p>${question}</p><p class="figure-note">${h(r.title)} · ${h(r.court)} · ${date(r.date)}</p><button class="small" data-action="case" data-id="${r.id}">Read the record and source →</button></article>`;
}
function findingsTeaching(){
 return findingSection('teaching','Bring the findings into a class or workshop','The patterns suggest several useful teaching questions. These are proposed exercises, not causal conclusions established by the study.',
 `<div class="teaching-grid"><article><h3>What would a complete check involve?</h3><p>Have students connect each proposition to a source passage, then verify the quotation, pinpoint, procedural posture, and current status. Include a draft in which every case exists but the analysis is still wrong.</p></article><article><h3>Who is responsible at the handoff?</h3><p>Give groups different roles: researcher, drafter, signer, and supervisor. Ask each group what it must check and what evidence of review it would need from the others.</p></article><article><h3>What changes after an editing pass?</h3><p>Let learners compare an original draft with an AI revision. Ask them to separate stylistic improvements from changes to citations, quotations, and the scope of the legal claims.</p></article><article><h3>What happens after the error is discovered?</h3><p>Ask students to prepare a correction plan and a candid explanation. Discuss how the plan addresses the court, the client, and anyone else who may have relied on the filing.</p></article></div>`+
 `<div class="teaching-grid">${teachingCase('Barteca','Checking existence versus checking support','What further checks would be needed after confirming that the cited cases exist?')}${teachingCase('Wadsworth','Review by the signing lawyer','What should the signer verify when someone else prepared the draft?')}${teachingCase('Withers','The response after discovery','What would a credible correction and review process look like after the court raises a problem?')}${teachingCase('Couvrette','Understanding monetary consequences','Which amounts are fines, which are fees or costs, and which order imposed each?')}</div>`+
 `<div class="actions finding-tools">${config.practice?'<button class="primary" data-action="go" data-route="practice">Open practice exercises</button>':''}<button data-action="go" data-route="review">Open review tools</button><button data-action="findings-print">Print or save this reading page</button><button data-action="findings-export">Export findings for teaching</button></div>`,'teaching');
}
function findings(){
 const includeStudy=config.study&&!dataset.meta.custom;
 const sections=FINDING_SECTIONS.filter(([id])=>includeStudy||['people','trends'].includes(id));
 const people=participantRows(records),prose=people[1][1];
 const custom=dataset.meta.custom;
 return `<div class="findings-page" data-version="educator-overview-v2">`+
 heading(h(config.organization)+' / '+(custom?'Research overview':'Research for legal educators'),h(custom?config.name:'What the AI cases tell us about legal practice'),h(config.intro),`<button class="small" data-action="findings-print">Print this page</button>`)+
 `<div class="reading-note"><p>${includeStudy?`This page brings together <strong>${n(records.length)} public decision records</strong> (${date(dataset.meta.snapshot)}) and the published findings from a <strong>450-order study of U.S. lawyer-related cases</strong> (September 2, 2026). Dates and denominators are shown with each chart; percentages are rounded.`:`This page summarizes all <strong>${n(records.length)} records</strong> in the active dataset. It does not apply filters left in the case browser.`} These are reported problems, not a measure of how often AI use goes wrong.</p>${activeCount()||ui.onlySaved?'<p class="figure-note">Your case-browser filters are still available in Browse decisions. They do not narrow this reading page.</p>':''}</div>`+
 (includeStudy?`<div class="stats finding-highlights">${stat('Pro se share of database',pct(prose,records.length),`${n(prose)} of ${n(records.length)} decision records involve self-represented litigants.`)}${stat('Median time since admission','21 years','Among the 394 lawyers with a verified admission year in the study.')}${stat('Solo or small-firm practice','83%','329 of 395 private-practice lawyers were solo or at firms of 2–10.')}${stat('Defects without invented cases','28%','128 of 450 orders involved errors without an invented case.')} </div>`:'')+
 `<nav class="finding-jumps" aria-label="Sections on this page"><span>On this page</span>${sections.map(([id,label])=>findingJump(id,label)).join('')}</nav>`+
 findingsPeople()+
 (includeStudy?findingsExperience()+findingsCourts()+findingsWorkflows()+findingsErrors()+findingsResponses():'')+
 findingsTrends(includeStudy)+
 (includeStudy?findingsTeaching():'')+
 `<section class="finding-section finding-method"><h2>What these findings can—and cannot—tell us</h2><p>The public database contains decision-level records, which can include repeated orders in the same matter, alleged AI use, and disputed entries. It does not establish that every person listed was sanctioned or that every reported defect was caused by AI.</p>${includeStudy?'<p>The additional study used a single AI-assisted coding pass without a second coder or an intercoder-reliability measurement. Its 450 orders, 420 identified lawyers, 394 resolved admission years, and 395 firm-size classifications are different denominators. The anonymous aggregates are available here; the underlying person-level workbooks are not included.</p>':''}<p>A concentration of cases in a group does not establish that the group is more likely to make an error. Comparing risk would require an appropriate count of lawyers, filings, or AI uses outside these reported cases.</p><p class="figure-note">Database: ${h(dataset.meta.author||'Source author not specified')} · ${h(dataset.meta.license||'Reuse terms not specified')}. ${includeStudy?'Supplemental analyses: September 2, 2026 snapshot; sample sizes are shown with each figure.':''} The presentation and teaching suggestions are written for this version.</p><div class="actions"><button class="small" data-action="go" data-route="sources">Sources and methods</button><button class="small" data-action="go" data-route="decisions">Browse the underlying records</button>${findingJump('top','Back to top')}</div></section></div>`;
}
function scrollToFinding(id,focus=true){
 const target=id==='top'?document.querySelector('.findings-page'):document.getElementById('finding-'+id);
 if(!target)return;
 target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
 if(focus){const title=target.querySelector('h2,h1');if(title){title.setAttribute('tabindex','-1');title.focus({preventScroll:true});}}
}
function findingsExport(){
 const main=document.querySelector('.findings-page');if(!main)return;
 let text='# '+main.querySelector('h1').innerText+'\n\n';
 main.querySelectorAll('.reading-note>p,.finding-highlights .stat,.finding-section').forEach(el=>{text+=el.innerText+'\n\n';});
 text+='\nPublic database: '+(dataset.meta.source||'Not supplied')+'\n';
 if(config.study&&!dataset.meta.custom)text+='Supplemental analyses: '+F.meta.snapshot+' snapshot. These aggregates use separate samples and were not recomputed from the current database export. See Sources and methods in this explorer.\n';
 download('ai-cases-teaching-findings.txt',text);
}
