const assert=require('node:assert/strict'),fs=require('node:fs'),C=require('../src/core.js');let passed=0;function check(name,fn){fn();passed++;console.log('PASS '+name);}
check('unknown source sentinel is not a dollar',()=>assert.equal(C.amount('1 USD').value,null));
check('custom dataset may contain a literal one',()=>assert.equal(C.amount('1 USD',false).value,1));
check('missing amount is not zero',()=>assert.equal(C.amount('').value,null));
check('zero can be a known value',()=>assert.equal(C.amount('0 USD').value,0));
check('currency missing stays missing',()=>assert.equal(C.amount('5000').currency,''));
check('no unsupported aggregate currency parsing',()=>assert.equal(C.amount('100 USD; 200 EUR').status,'unparsed'));
check('CSV quoted commas and line breaks',()=>assert.deepEqual(C.parseCSV('a,b\r\n"one,two","three\nfour"\r\n').rows,[['one,two','three\nfour']]));
check('CSV escaped quotes',()=>assert.equal(C.parseCSV('a\n"x""y"').rows[0][0],'x"y'));
check('rejects broken CSV quotes',()=>assert.throws(()=>C.parseCSV('a\n"oops')));
check('rejects uneven CSV rows',()=>assert.throws(()=>C.parseCSV('a,b\nx')));
check('spreadsheet formula injection escaped',()=>assert(C.toCSV([['=1+1']]).includes("'=1+1")));
check('safe URL rejects script scheme',()=>assert.equal(C.safeURL('javascript:alert(1)'),''));
check('source relative URL resolves correctly',()=>assert.equal(C.safeURL('/documents/1/x.pdf'),'https://www.damiencharlotin.com/documents/1/x.pdf'));
check('state field countries not US states',()=>assert.equal(C.inferState('SC New York',['USA']),'NY'));
check('West Virginia distinct from Virginia',()=>assert.equal(C.inferState('S.D. West Virginia',['USA']),'WV'));
check('not inferring New York outside USA',()=>assert.equal(C.inferState('New York',['Canada']),''));
check('circuit remains unassigned',()=>assert.equal(C.inferState('9th Cir.',['USA']),''));
check('validates leap date',()=>assert.equal(C.validDate('2025-02-29'),''));
check('real leap date valid',()=>assert.equal(C.validDate('2024-02-29'),'2024-02-29'));
check('exact quote comparison detects changed negation',()=>assert.equal(C.compareText('does not compel','does compel').equal,false));
check('normalization ignores only whitespace',()=>assert.equal(C.compareText('does  not\ncompel','does not compel',true).equal,true));
check('exact comparison keeps whitespace',()=>assert.equal(C.compareText('A  B','A B').equal,false));
check('HTML is escaped',()=>assert.equal(C.escape('<script>'),'&lt;script&gt;'));
const csv=C.parseCSV(fs.readFileSync('data/source.csv','utf8'));csv.meta={oneIsUnknown:true};const rows=C.normalizeDataset(csv);
check('full snapshot loaded',()=>assert.equal(rows.length,2036));
check('US overlap count matches source',()=>assert.equal(C.filterRows(rows,{country:'USA'}).length,1393));
check('alleged flags match source',()=>assert.equal(rows.filter(r=>r.alleged).length,20));
check('vendor disputed flags match source',()=>assert.equal(rows.filter(r=>r.disputed).length,12));
check('lawyer actor overlap matches source',()=>assert.equal(C.filterRows(rows,{actor:'Lawyer'}).length,809));
check('error deduplication matches source',()=>assert.equal(C.filterRows(rows,{type:'Fabricated'}).length,1686));
check('no repeated type inflates counts',()=>assert.equal(C.count(rows,'types').find(x=>x[0]==='Misrepresented')[1],852));
check('cumulative series total matches dated rows',()=>assert.equal(C.series(rows).at(-1).total,rows.filter(r=>r.date).length));
check('median even sample',()=>assert.equal(C.median([5,1,3,7]),4));
check('blank source has no invented URL',()=>assert.equal(C.safeURL(''),''));
console.log(JSON.stringify({passed,failed:0,records:rows.length}));
